version: 2
updates:
  - package-ecosystem: npm
    directory: "/builds/mcp_release"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/builds/typescript"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/builds/typescript/client_web"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
