import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { z, type ZodType } from "zod";

import { AuditEventSchema, LifecycleDiagnosticEventSchema, ResumeRecoveryReconciliationAuditDetailsSchema } from "./audit.js";
import {
  AppArtifactRecordSchema,
  AppArtifactRegistrationRequestSchema,
  AppExportFinalizeRequestSchema,
  AppExportPreparedResultSchema,
  AppExportPrepareRequestSchema,
  AppExportReceiptRecordSchema,
  AppSafeExportReceiptProjectionSchema,
} from "./app-artifacts.js";
import {
  AppIdentitySchema,
  AppOperationBindingSchema,
  AppRetentionPolicySchema,
  AppActionDescriptorSchema,
  AppActionJsonSchemaBodySchema,
  AppActionSchemaResourceSchema,
  CapabilityRegistrationSchema,
  CapabilityRequestSchema,
  CatalogPresentationSchema,
  AppContextRequestDescriptorSchema,
  DataAdapterRegistrationSchema,
  FirstPartyAppRegistrationSchema,
  GenericPackageManifestSchema,
  InferencePurposeRegistrationSchema,
  InferencePurposeRequestSchema,
  AppPresentationProfileSchema,
  AppPresentationSetSchema,
  PrimaryUiResourceDescriptorSchema,
  ResolvedAppDescriptorSchema,
  AppResourceDescriptorSchema,
  ChatWorkspaceDescriptorSchema,
  VerifiedFirstPartyPackageSchema,
  WorkspaceDocumentDescriptorSchema,
} from "./app-registry.js";
import {
  AppDocumentAuditProjectionSchema,
  AppDocumentStorageDeletionRequestSchema,
  AppDocumentStorageDeletionResultSchema,
  AppDocumentStorageListResultSchema,
  AppDocumentRecordSchema,
  AppDocumentStorageAuthoritySchema,
  AppDocumentStorageMutationRequestSchema,
  AppDocumentStorageMutationResultSchema,
  AppDocumentTombstoneRecordSchema,
} from "./app-storage.js";
import { CompatibilityMatrixSchema } from "./common.js";
import {
  ArtifactRecordSchema,
  ArtifactParityReportRecordSchema,
  CareerContextProjectionSchema,
  CareerFactRecordSchema,
  CraftQualityReportRecordSchema,
  CraftRepairOperationRecordSchema,
  CareerReturnSummarySchema,
  DefinitionApprovalEvidenceSchema,
  DefinitionComparisonResultSchema,
  ExportReceiptRecordSchema,
  FrozenQualityRegressionManifestSchema,
  InterviewProgressRecordSchema,
  GuidanceResultSchema,
  ImpactAnalysisResultSchema,
  RememberedMatchResultSchema,
  JobEvidenceValueSchema,
  JobDescriptionRecordSchema,
  JobEvidenceCoverageRecordSchema,
  LineageGraphSchema,
  MigrationRecordSchema,
  ResumeDefinitionRecordSchema,
  ResumeQualityStateSchema,
  ResumeStrategyRecordSchema,
  ResumeRevisionRequestRecordSchema,
  SourceRecordSchema,
  TailoredVariantRecordSchema,
  TargetFitAnalysisRecordSchema,
} from "./data.js";
import {
  MigrationCompatibilityPolicySchema,
  MigrationProvenanceSchema,
  OwnerSafeResumeDataStateSchema,
  ResumeDataCapabilityContextSchema,
  ResumeDataCapabilityRequestSchema,
  ResumeDataCapabilityResultSchema,
  RetentionMatrixSchema,
} from "./data-conformance.js";
import { ContractErrorSchema } from "./errors.js";
import {
  InferenceErrorSchema,
  InferenceOutcomeMetadataSchema,
  InferenceRequestSchema,
  InferenceResultSchema,
  ModelCompatibilityEntrySchema,
} from "./inference.js";
import { PURPOSE_RESULT_SCHEMAS } from "../../resume-inference/results.js";
import {
  ResumeRecoveryOperationLifecycleProjectionSchema,
  ResumeRecoveryReconciliationQuerySchema,
} from "../../app-capabilities/recovery-reconciliation.js";
import { ResumeQualityReportSchema, SyntheticQualityFixtureSchema } from "../../resume-inference/quality.js";
import {
  LifecycleOperationSchema,
  LifecycleRecordSchema,
  LifecycleResultSchema,
  LifecycleTransitionSchema,
  OperationRecordSchema,
} from "./lifecycle.js";
import {
  AppLifecycleStoragePolicySchema,
  MixedVersionPolicySchema,
  ResumeLifecycleDataAdapterRequestSchema,
  ResumeLifecycleDataAdapterResultSchema,
} from "./lifecycle-foundation.js";
import { BridgeMessageSchema, BridgePolicySchema, CompleteMcpResultSchema, McpAppResourceSchema } from "./mcp-app.js";
import {
  CapabilityGrantSchema,
  CapabilityDiffSchema,
  CapabilityTokenSchema,
  PackageDescriptorSchema,
  ArchiveEntryContractSchema,
  PackageManifestSchema,
  PackageSourceIndexSchema,
  PackageTrustSchema,
  RevocationFreshnessPolicySchema,
  RevocationListSchema,
  SupervisorPolicySchema,
  TrustRootSchema,
} from "./package.js";
import {
  EndpointDescriptorSchema,
  RuntimeDescriptorSchema,
  RuntimeIdentitySchema,
  SupervisorHealthRequestSchema,
  SupervisorHealthResultSchema,
  SupervisorCleanupRequestSchema,
  SupervisorCleanupResultSchema,
  SupervisorReadyRequestSchema,
  SupervisorReadyResultSchema,
  SupervisorReconcileRequestSchema,
  SupervisorReconcileResultSchema,
  SupervisorRegistrationRequestSchema,
  SupervisorRegistrationResultSchema,
  SupervisorStartRequestSchema,
  SupervisorStartResultSchema,
  SupervisorStopRequestSchema,
  SupervisorStopResultSchema,
  SupervisorTokenRevocationRequestSchema,
  SupervisorTokenRevocationResultSchema,
} from "./supervisor.js";
import {
  AppCapabilityAuthoritySchema,
  AppInferenceCancelSchema,
  AppInferenceEventSchema,
  AppInferenceRequestSchema,
  AppsBridgeEnvelopeSchema,
  AppsBridgeJsonRpcMessageSchema,
  AppViewStateSchema,
  McpAppsResourceDescriptorSchema,
  McpAppsToolSchema,
  McpNegotiatedPeerSchema,
  McpSupportProfileSchema,
  Spec05CompleteResultSchema,
  Spec05DependencyProfileSchema,
  Spec05DiagnosticSchema,
  Spec05FoundationBundleSchema,
  Spec05ParityEvidenceSchema,
} from "./spec-05-foundation.js";

export const JSON_SCHEMA_AUTHORITIES = {
  "app-identity": AppIdentitySchema,
  "app-operation-binding": AppOperationBindingSchema,
  "app-retention-policy": AppRetentionPolicySchema,
  "app-action-descriptor": AppActionDescriptorSchema,
  "app-action-json-schema-body": AppActionJsonSchemaBodySchema,
  "app-action-schema-resource": AppActionSchemaResourceSchema,
  "app-artifact-record": AppArtifactRecordSchema,
  "app-artifact-registration-request": AppArtifactRegistrationRequestSchema,
  "app-export-finalize-request": AppExportFinalizeRequestSchema,
  "app-export-prepared-result": AppExportPreparedResultSchema,
  "app-export-prepare-request": AppExportPrepareRequestSchema,
  "app-export-receipt-record": AppExportReceiptRecordSchema,
  "app-safe-export-receipt-projection": AppSafeExportReceiptProjectionSchema,
  "app-document-audit-projection": AppDocumentAuditProjectionSchema,
  "app-document-storage-deletion-request": AppDocumentStorageDeletionRequestSchema,
  "app-document-storage-deletion-result": AppDocumentStorageDeletionResultSchema,
  "app-document-storage-list-result": AppDocumentStorageListResultSchema,
  "app-document-record": AppDocumentRecordSchema,
  "app-document-storage-authority": AppDocumentStorageAuthoritySchema,
  "app-document-storage-mutation-request": AppDocumentStorageMutationRequestSchema,
  "app-document-storage-mutation-result": AppDocumentStorageMutationResultSchema,
  "app-document-tombstone-record": AppDocumentTombstoneRecordSchema,
  "app-capability-request": CapabilityRequestSchema,
  "app-context-request-descriptor": AppContextRequestDescriptorSchema,
  "app-inference-purpose-request": InferencePurposeRequestSchema,
  "app-catalog-presentation": CatalogPresentationSchema,
  "app-presentation-profile": AppPresentationProfileSchema,
  "app-presentation-set": AppPresentationSetSchema,
  "app-primary-resource": PrimaryUiResourceDescriptorSchema,
  "app-resource-descriptor": AppResourceDescriptorSchema,
  "app-capability-registration": CapabilityRegistrationSchema,
  "app-inference-purpose-registration": InferencePurposeRegistrationSchema,
  "app-data-adapter-registration": DataAdapterRegistrationSchema,
  "chat-workspace-descriptor": ChatWorkspaceDescriptorSchema,
  "first-party-app-registration": FirstPartyAppRegistrationSchema,
  "generic-package-manifest": GenericPackageManifestSchema,
  "verified-first-party-package": VerifiedFirstPartyPackageSchema,
  "resolved-app-descriptor": ResolvedAppDescriptorSchema,
  "workspace-document-descriptor": WorkspaceDocumentDescriptorSchema,
  "app-capability-authority": AppCapabilityAuthoritySchema,
  "app-inference-cancel": AppInferenceCancelSchema,
  "app-inference-event": AppInferenceEventSchema,
  "app-inference-request": AppInferenceRequestSchema,
  "apps-bridge-envelope": AppsBridgeEnvelopeSchema,
  "apps-bridge-jsonrpc-message": AppsBridgeJsonRpcMessageSchema,
  "app-view-state": AppViewStateSchema,
  "app-lifecycle-storage-policy": AppLifecycleStoragePolicySchema,
  "archive-entry-contract": ArchiveEntryContractSchema,
  "artifact-record": ArtifactRecordSchema,
  "artifact-parity-report-record": ArtifactParityReportRecordSchema,
  "audit-event": AuditEventSchema,
  "bridge-message": BridgeMessageSchema,
  "bridge-policy": BridgePolicySchema,
  "capability-grant": CapabilityGrantSchema,
  "capability-diff": CapabilityDiffSchema,
  "capability-token": CapabilityTokenSchema,
  "career-fact-record": CareerFactRecordSchema,
  "craft-quality-report-record": CraftQualityReportRecordSchema,
  "craft-repair-operation-record": CraftRepairOperationRecordSchema,
  "career-context-projection": CareerContextProjectionSchema,
  "career-return-summary": CareerReturnSummarySchema,
  "definition-approval-evidence": DefinitionApprovalEvidenceSchema,
  "definition-comparison-result": DefinitionComparisonResultSchema,
  "data-capability-context": ResumeDataCapabilityContextSchema,
  "data-capability-request": ResumeDataCapabilityRequestSchema,
  "data-capability-result": ResumeDataCapabilityResultSchema,
  "compatibility-matrix": CompatibilityMatrixSchema,
  "complete-mcp-result": CompleteMcpResultSchema,
  "contract-error": ContractErrorSchema,
  "export-receipt-record": ExportReceiptRecordSchema,
  "frozen-quality-regression-manifest": FrozenQualityRegressionManifestSchema,
  "inference-request": InferenceRequestSchema,
  "inference-error": InferenceErrorSchema,
  "inference-outcome-metadata": InferenceOutcomeMetadataSchema,
  "inference-result": InferenceResultSchema,
  "inference-result-interview-assist": PURPOSE_RESULT_SCHEMAS.interview_assist,
  "inference-result-general-resume-draft": PURPOSE_RESULT_SCHEMAS.general_resume_draft,
  "inference-result-job-description-analyze": PURPOSE_RESULT_SCHEMAS.job_description_analyze,
  "inference-result-requirement-evidence-match": PURPOSE_RESULT_SCHEMAS.requirement_evidence_match,
  "inference-result-tailoring-plan": PURPOSE_RESULT_SCHEMAS.tailoring_plan,
  "inference-result-targeted-resume-draft": PURPOSE_RESULT_SCHEMAS.targeted_resume_draft,
  "inference-result-resume-revision-classify": PURPOSE_RESULT_SCHEMAS.resume_revision_classify,
  "inference-result-resume-revision-draft": PURPOSE_RESULT_SCHEMAS.resume_revision_draft,
  "inference-result-resume-guidance": PURPOSE_RESULT_SCHEMAS.resume_guidance,
  "inference-result-resume-strategy": PURPOSE_RESULT_SCHEMAS.resume_strategy,
  "inference-result-resume-craft-evaluate": PURPOSE_RESULT_SCHEMAS.resume_craft_evaluate,
  "inference-result-resume-craft-repair": PURPOSE_RESULT_SCHEMAS.resume_craft_repair,
  "guidance-result": GuidanceResultSchema,
  "impact-analysis-result": ImpactAnalysisResultSchema,
  "remembered-match-result": RememberedMatchResultSchema,
  "job-description-record": JobDescriptionRecordSchema,
  "interview-progress-record": InterviewProgressRecordSchema,
  "job-evidence-value": JobEvidenceValueSchema,
  "job-evidence-coverage-record": JobEvidenceCoverageRecordSchema,
  "lineage-graph": LineageGraphSchema,
  "lifecycle-transition": LifecycleTransitionSchema,
  "lifecycle-record": LifecycleRecordSchema,
  "lifecycle-operation": LifecycleOperationSchema,
  "lifecycle-result": LifecycleResultSchema,
  "lifecycle-diagnostic-event": LifecycleDiagnosticEventSchema,
  "mixed-version-policy": MixedVersionPolicySchema,
  "mcp-app-resource": McpAppResourceSchema,
  "mcp-apps-resource-descriptor": McpAppsResourceDescriptorSchema,
  "mcp-apps-tool": McpAppsToolSchema,
  "mcp-negotiated-peer": McpNegotiatedPeerSchema,
  "mcp-support-profile": McpSupportProfileSchema,
  "migration-record": MigrationRecordSchema,
  "migration-compatibility-policy": MigrationCompatibilityPolicySchema,
  "migration-provenance": MigrationProvenanceSchema,
  "model-compatibility-entry": ModelCompatibilityEntrySchema,
  "operation-record": OperationRecordSchema,
  "owner-safe-data-state": OwnerSafeResumeDataStateSchema,
  "package-descriptor": PackageDescriptorSchema,
  "package-manifest": PackageManifestSchema,
  "package-source-index": PackageSourceIndexSchema,
  "package-trust": PackageTrustSchema,
  "revocation-list": RevocationListSchema,
  "revocation-freshness-policy": RevocationFreshnessPolicySchema,
  "resume-definition-record": ResumeDefinitionRecordSchema,
  "resume-recovery-reconciliation-audit-details": ResumeRecoveryReconciliationAuditDetailsSchema,
  "resume-recovery-operation-lifecycle-projection": ResumeRecoveryOperationLifecycleProjectionSchema,
  "resume-recovery-reconciliation-query": ResumeRecoveryReconciliationQuerySchema,
  "resume-quality-state": ResumeQualityStateSchema,
  "resume-strategy-record": ResumeStrategyRecordSchema,
  "resume-revision-request-record": ResumeRevisionRequestRecordSchema,
  "resume-quality-report": ResumeQualityReportSchema,
  "resume-quality-synthetic-fixture": SyntheticQualityFixtureSchema,
  "resume-lifecycle-data-adapter-request": ResumeLifecycleDataAdapterRequestSchema,
  "resume-lifecycle-data-adapter-result": ResumeLifecycleDataAdapterResultSchema,
  "retention-matrix": RetentionMatrixSchema,
  "source-record": SourceRecordSchema,
  "spec-05-complete-result": Spec05CompleteResultSchema,
  "spec-05-dependency-profile": Spec05DependencyProfileSchema,
  "spec-05-diagnostic": Spec05DiagnosticSchema,
  "spec-05-foundation-bundle": Spec05FoundationBundleSchema,
  "spec-05-parity-evidence": Spec05ParityEvidenceSchema,
  "supervisor-policy": SupervisorPolicySchema,
  "supervisor-endpoint-descriptor": EndpointDescriptorSchema,
  "supervisor-runtime-descriptor": RuntimeDescriptorSchema,
  "supervisor-runtime-identity": RuntimeIdentitySchema,
  "supervisor-start-request": SupervisorStartRequestSchema,
  "supervisor-start-result": SupervisorStartResultSchema,
  "supervisor-ready-request": SupervisorReadyRequestSchema,
  "supervisor-ready-result": SupervisorReadyResultSchema,
  "supervisor-health-request": SupervisorHealthRequestSchema,
  "supervisor-health-result": SupervisorHealthResultSchema,
  "supervisor-cleanup-request": SupervisorCleanupRequestSchema,
  "supervisor-cleanup-result": SupervisorCleanupResultSchema,
  "supervisor-registration-request": SupervisorRegistrationRequestSchema,
  "supervisor-registration-result": SupervisorRegistrationResultSchema,
  "supervisor-stop-request": SupervisorStopRequestSchema,
  "supervisor-stop-result": SupervisorStopResultSchema,
  "supervisor-token-revocation-request": SupervisorTokenRevocationRequestSchema,
  "supervisor-token-revocation-result": SupervisorTokenRevocationResultSchema,
  "supervisor-reconcile-request": SupervisorReconcileRequestSchema,
  "supervisor-reconcile-result": SupervisorReconcileResultSchema,
  "trust-root": TrustRootSchema,
  "tailored-variant-record": TailoredVariantRecordSchema,
  "target-fit-analysis-record": TargetFitAnalysisRecordSchema,
} as const satisfies Record<string, ZodType>;

export function createJsonSchemaCatalog(): Record<string, unknown> {
  const genericAuthorities = new Set([
    "app-identity",
    "app-operation-binding",
    "app-action-descriptor",
    "app-action-json-schema-body",
    "app-action-schema-resource",
    "app-artifact-record",
    "app-artifact-registration-request",
    "app-export-finalize-request",
    "app-export-prepared-result",
    "app-export-prepare-request",
    "app-export-receipt-record",
    "app-safe-export-receipt-projection",
    "app-document-audit-projection",
    "app-document-record",
    "app-document-storage-authority",
    "app-document-storage-mutation-request",
    "app-document-storage-mutation-result",
    "app-capability-request",
    "app-context-request-descriptor",
    "app-inference-purpose-request",
    "app-catalog-presentation",
    "app-presentation-profile",
    "app-presentation-set",
    "app-primary-resource",
    "app-resource-descriptor",
    "app-capability-registration",
    "app-inference-purpose-registration",
    "app-data-adapter-registration",
    "chat-workspace-descriptor",
    "first-party-app-registration",
    "generic-package-manifest",
    "verified-first-party-package",
    "resolved-app-descriptor",
    "workspace-document-descriptor",
  ]);
  return Object.fromEntries(
    Object.entries(JSON_SCHEMA_AUTHORITIES).map(([name, schema]) => [
      name,
      {
        $id: genericAuthorities.has(name)
          ? `https://schemas.braindrive.ai/app-platform/v1/${name}.schema.json`
          : `https://schemas.braindrive.ai/resume-builder/v1/${name}.schema.json`,
        ...z.toJSONSchema(schema, {
          target: "draft-2020-12",
          io: "input",
          unrepresentable: "any",
        }),
      },
    ]),
  );
}

async function main(): Promise<void> {
  const directory = resolve(dirname(fileURLToPath(import.meta.url)), "schemas", "v1");
  await mkdir(directory, { recursive: true });
  const catalog = createJsonSchemaCatalog();
  for (const [name, schema] of Object.entries(catalog)) {
    await writeFile(resolve(directory, `${name}.schema.json`), `${JSON.stringify(schema, null, 2)}\n`, "utf8");
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
