"""add required_services_runtime to plugin

Revision ID: 5d073fe444c9
Revises: 219da9748f46
Create Date: 2025-08-25 21:27:45.545834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d073fe444c9'
down_revision: Union[str, None] = '219da9748f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_service_runtime',
       sa.Column('id', sa.String(), nullable=False),
       sa.Column('plugin_id', sa.String(), nullable=False),
       sa.Column('plugin_slug', sa.String(), nullable=False),
       sa.Column('name', sa.String(), nullable=False),
       sa.Column('source_url', sa.String(), nullable=True),
       sa.Column('type', sa.String(), nullable=True),
       sa.Column('install_command', sa.Text(), nullable=True),
       sa.Column('start_command', sa.Text(), nullable=True),
       sa.Column('healthcheck_url', sa.String(), nullable=True),
       sa.Column('required_env_vars', sa.Text(), nullable=True),
       sa.Column('status', sa.String(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('user_id', sa.String(length=32), nullable=False),
       sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_plugin_service_runtime_user_id'),
       sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plugin_service_runtime', schema=None) as batch_op:
       batch_op.create_index(batch_op.f('ix_plugin_service_runtime_id'), ['id'], unique=False)
       batch_op.create_index(batch_op.f('ix_plugin_service_runtime_plugin_id'), ['plugin_id'], unique=False)
       batch_op.create_index(batch_op.f('ix_plugin_service_runtime_plugin_slug'), ['plugin_slug'], unique=False)

    with op.batch_alter_table('plugin', schema=None) as batch_op:
       batch_op.add_column(sa.Column('required_services_runtime', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin', schema=None) as batch_op:
       batch_op.drop_column('required_services_runtime')

    with op.batch_alter_table('plugin_service_runtime', schema=None) as batch_op:
       batch_op.drop_index(batch_op.f('ix_plugin_service_runtime_plugin_slug'))
       batch_op.drop_index(batch_op.f('ix_plugin_service_runtime_plugin_id'))
       batch_op.drop_index(batch_op.f('ix_plugin_service_runtime_id'))

    op.drop_table('plugin_service_runtime')
    # ### end Alembic commands ###
