"""Add nested routes support

Revision ID: 7a9b2c8d3e4f
Revises: 6f8a2c9d1e7b
Create Date: 2025-03-17 09:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7a9b2c8d3e4f'
down_revision: Union[str, None] = '6f8a2c9d1e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the pages table exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'pages' in tables:
        # Add new columns to the pages table
        op.add_column('pages', sa.Column('route_segment', sa.String(length=255), nullable=True))
        op.add_column('pages', sa.Column('parent_type', sa.String(length=50), nullable=True))
        op.add_column('pages', sa.Column('is_parent_page', sa.Boolean(), nullable=True, default=False))
        
        # Populate route_segment from route for existing pages
        op.execute("UPDATE pages SET route_segment = route WHERE route_segment IS NULL")
        
        # Set default parent_type to 'page'
        op.execute("UPDATE pages SET parent_type = 'page' WHERE parent_type IS NULL")
        
        # Update full routes for child pages
        op.execute("""
        UPDATE pages 
        SET route = (
            SELECT parent.route || '/' || pages.route_segment 
            FROM pages parent 
            WHERE parent.route = pages.parent_route
        )
        WHERE parent_route IS NOT NULL
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the pages table exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'pages' in tables:
        # Remove the new columns
        op.drop_column('pages', 'is_parent_page')
        op.drop_column('pages', 'parent_type')
        op.drop_column('pages', 'route_segment')
    # ### end Alembic commands ###
